### ISSUE TITLE
Using the with a portable Vapoursynth R65 version,..

### ISSUE THREAD

**Issue by Selur** [Jaded-Encoding-Thaumaturgy/vs-denoise#121]
I'm trying to install vs-denoise in a portable Vapoursynth R65 version using:
`python -m pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git`
and get:
```
F:\Hybrid\64bit\Vapoursynth>python -m pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git
Collecting git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git
  Cloning https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git to c:\users\selur\appdata\local\temp\pip-req-build-iwnowtha
  Running command git clone --filter=blob:none --quiet https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git 'C:\Users\Selur\AppData\Local\Temp\pip-req-build-iwnowtha'
  Resolved https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git to commit ff32b55dc7a0ad44be3988d1233a0e60d5c677d9
  Preparing metadata (setup.py) ... done
Collecting VapourSynth>=65 (from vsdenoise==2.5.1)
  Using cached VapourSynth-66.zip (764 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-tozppxvu\vapoursynth_8caa2a15303c4c5d95026f7382681b74\setup.py", line 69, in <module>
          dll_path = query(winreg.HKEY_LOCAL_MACHINE, REGISTRY_PATH, REGISTRY_KEY)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-tozppxvu\vapoursynth_8caa2a15303c4c5d95026f7382681b74\setup.py", line 43, in query
          reg_key = winreg.OpenKey(hkey, path, 0, winreg.KEY_READ)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-tozppxvu\vapoursynth_8caa2a15303c4c5d95026f7382681b74\setup.py", line 72, in <module>
          raise OSError("Couldn't detect vapoursynth installation path")
      OSError: Couldn't detect vapoursynth installation path
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Site note: It works fine with R66, but there the portable package was reworked and a VapoursynthR66 wheel file was installed.  (So it's a problem with portable Vapoursynth before R66.

=> Is there some environment variable I can set so that this does not happen with R65?

**Comment by Setsugennoao** [comment]
Has nothing to do with the package, open a relevant issue in the vapoursynth repo.
